[workspace]
members = [
	"eth2/attester",
	"eth2/block_proposer",
	"eth2/fork_choice",
	"eth2/operation_pool",
	"eth2/state_processing",
	"eth2/state_processing/yaml_utils",
	"eth2/types",
	"eth2/utils/bls",
	"eth2/utils/boolean-bitfield",
	"eth2/utils/hashing",
	"eth2/utils/honey-badger-split",
	"eth2/utils/merkle_proof",
	"eth2/utils/int_to_bytes",
	"eth2/utils/serde_hex",
	"eth2/utils/slot_clock",
	"eth2/utils/ssz",
	"eth2/utils/ssz_derive",
	"eth2/utils/swap_or_not_shuffle",
	"eth2/utils/fisher_yates_shuffle",
    "eth2/utils/test_random_derive",
	"beacon_node",
	"beacon_node/db",
	"beacon_node/client",
	"beacon_node/network",
	"beacon_node/eth2-libp2p",
    "beacon_node/rpc",
	"beacon_node/version",
	"beacon_node/beacon_chain",
	"beacon_node/beacon_chain/test_harness",
	"protos",
	"validator_client",
	"account_manager",
]
